language: php

matrix:
    include:
        - php: 5.6
        - php: 7
        - php: 7.1
        - php: 7.2
        - php: 7.3
    fast_finish: true

before_install:
    - composer self-update

before_script:
    - composer install

script:
    - vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml tests/

after_success:
  - travis_retry php vendor/bin/coveralls
